$:
  vscode:
    - services:
        - vscode
        - docker
      docker:
        image: docker.cnb.cool/arsrna/dev-image/nodejs
        volumes:
          - /root/.bun/install/cache
          - /root/.npm
      imports:
        - https://cnb.cool/arsrna/env/-/blob/main/npm.yml
      runner:
        cpus: 16
      stages:
        - name: 安装依赖
          script: bun i
        - name: 构建
          script: bun run build

  push:
    sync_to_github:
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          imports:
            - https://cnb.cool/arsrna/env/-/blob/main/git.yaml
          settings:
            target_url: https://github.com/ArSrNa/os-vite-react-template.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            git_email: "root@arsrna.cn"

    coverage_test:
      docker:
        image: node:24
        volumes:
          - /root/.bun/install/cache
          - /root/.npm
      stages:
        - name: bun
          script: npm i -g bun
        - name: 测试覆盖率
          script:
            - bun i
            - bun test
        - name: coverage
          type: testing:coverage
          options:
            diffLines: 78 # 增量覆盖率红线
          exports:
            lines: LINES
            diff_pct: DIFF_LINES
        - name: result
          script: echo echo "LINES $LINES DIFF_LINES $DIFF_LINES"

  # tag push 时触发
  tag_push:
    - docker:
        image: docker.cnb.cool/arsrna/dev-env/node22:latest
        volumes:
          - /root/.bun/install/cache
          - /root/.npm
      runner:
        cpus: 16
      stages:
        - name: 构建部署
          script:
            - bun i
            - bun run build
            - echo $CNB_BRANCH
        - name: update version
          # 修改 package.json 中的version为当前tag，但不会提交代码
          script: npm version $CNB_BRANCH --no-git-tag-version
        - name: npm publish
          script:
            - npm publish

        - name: cnb-npm publish
          image: tencentcom/npm
          settings:
            username: $CNB_TOKEN_USER_NAME
            token: $CNB_TOKEN
            email: $CNB_COMMITTER_EMAIL
            registry: https://npm.cnb.cool/arsrna/os-npm/-/packages/
            folder: ./dist
            fail_on_version_conflict: false
